services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-app
    container_name: next-app
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
  
volumes:
  node_modules:
