import { ReactNode } from 'react';
import { Kaisei_Decol} from "next/font/google";
const KaiseiDecolFont = Kaisei_Decol({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <link rel="shortcut icon" type="image/png" href="https://animaproject.s3.amazonaws.com/home/favicon.png" />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="photo" />
        <link rel="stylesheet" type="text/css" href="css/jimbo-iphone-13-mini-top-u20206u27770u23450.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <script src="https://animaapp.s3.amazonaws.com/launchpad-static/launchpad.js"></script>
        <link rel="stylesheet" type="text/css" href="/style.css" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={KaiseiDecolFont.className}>{children}</body>
    </html>
  );
}
